import {chromium} from 'playwright';import http from 'node:http';import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath,pathToFileURL} from 'node:url';import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(!u.pathname.startsWith('/marinepath/')){res.writeHead(404);return res.end();}const rel=u.pathname.slice('/marinepath/'.length)||'index.html';if(rel.includes('..'))throw Error('Invalid path');const data=await fs.readFile(path.join(root,'_site',rel));res.setHeader('Content-Type',rel.endsWith('.json')?'application/json':rel.endsWith('.svg')?'image/svg+xml':'text/html; charset=utf-8');res.end(data);}catch{res.writeHead(404);res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port+'/marinepath/';const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1366,height:1000}});const errors=[],api=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/\/api\/|\/proxy\?/.test(r.url()))api.push(r.url());});let checks=0;const ok=(condition,msg)=>{assert.ok(condition,msg);checks++;console.log('PASS',msg);};
const fixture={schemaVersion:1,appVersion:'3.0.0',generatedAt:new Date().toISOString(),sources:{}};
for(const source of ['faststream','spinnaker','careernet','seacareer','marpro','navis'])fixture.sources[source]={jobs:[],status:'Connected',lastSuccessAt:new Date().toISOString(),warnings:[]};
fixture.sources.faststream.jobs=[{id:'test-engineer',source:'faststream',title:'Technical Superintendent - Tankers',company:'Fictional test company',location:'Athens, Greece',url:'https://example.org/jobs/1',desc:('Marine vessels. Chief Engineer STCW III/2 Class 1 CoC. Oil and chemical tankers. Dry docking, planned maintenance PMS, MAN engines. ISM, SOLAS, MARPOL. ').repeat(4),date:new Date().toISOString(),detailStatus:'digest',descriptionCoverage:'Extracted from full advert'}];
try{
 await page.route('**/data/jobs.json*',r=>r.fulfill({contentType:'application/json',body:JSON.stringify(fixture)}));await page.goto(base);await page.waitForSelector('#searchPlan h3');ok((await page.title()).includes('MarinePath'),'Pages subpath loads');ok(await page.locator('#snapshotInfo').isVisible(),'Snapshot timestamp visible');
 for(const tab of ['connections','settings','tracker','pipeline','search']){await page.click('[data-tab='+tab+']');ok(await page.locator('#tab-'+tab).isVisible(),'Navigation '+tab);}
 await page.click('#btnDemo');await page.click('#btnScan');await page.waitForFunction(()=>!running);ok(await page.locator('#results .job').count()===1,'Search matches static data without backend');ok(api.length===0,'No /api or /proxy requests');
 await page.locator('[data-detail]').first().click();await page.click('#dCover');ok((await page.locator('#letterBox').innerText()).length>250,'Local cover letter generated');await page.keyboard.press('Escape');await page.click('[data-save]');await page.click('[data-tab=tracker]');ok(await page.locator('.kb-card').count()===1,'Applications retain saved jobs');
 await page.click('[data-tab=search]');await page.setInputFiles('#pdfInput',path.join(root,'tests/embedded-cv.pdf'));await page.waitForFunction(()=>document.querySelector('#cv').value.includes('MARPOL'));ok(await page.evaluate(()=>state.cv.includes('STCW')),'Embedded-font PDF imports without external scripts');
 await page.evaluate(data=>document.getElementById('marinepathData').textContent=JSON.stringify(data),fixture);await page.unroute('**/data/jobs.json*');await page.route('**/data/jobs.json*',r=>r.abort());await page.click('#btnScan');await page.waitForFunction(()=>!running);ok(await page.evaluate(()=>lastScan.offline===true&&state.results.length===1),'Embedded fallback works when network fails');
 await page.unroute('**/data/jobs.json*');const stale=structuredClone(fixture);for(const s of Object.values(stale.sources))s.lastSuccessAt='2020-01-01T00:00:00Z';await page.route('**/data/jobs.json*',r=>r.fulfill({contentType:'application/json',body:JSON.stringify(stale)}));await page.click('[data-tab=search]');await page.click('#btnScan');await page.waitForFunction(()=>!running);ok((await page.locator('#scanStatus').innerText()).includes('72 hours'),'Stale data refused with explicit reason');ok(await page.evaluate(()=>state.results.length===1),'Stale-data failure preserves previous results');
 await page.unroute('**/data/jobs.json*');await page.route('**/data/jobs.json*',async r=>{await new Promise(resolve=>setTimeout(resolve,1500));await r.fulfill({contentType:'application/json',body:JSON.stringify(fixture)}).catch(()=>{});});await page.click('#btnScan');await page.click('#btnStop');await page.waitForFunction(()=>!running);ok(!await page.locator('#btnScan').isDisabled(),'Stop releases search button');
 await page.setViewportSize({width:390,height:844});ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile layout fits viewport');
 const filePage=await browser.newPage();await filePage.goto(pathToFileURL(path.join(root,'index.html')).href);await filePage.waitForSelector('#searchPlan h3');await filePage.evaluate(data=>document.getElementById('marinepathData').textContent=JSON.stringify(data),fixture);await filePage.click('#btnDemo');await filePage.click('#btnScan');await filePage.waitForFunction(()=>!running);ok(await filePage.locator('#results .job').count()===1,'Downloaded HTML works directly with file://');ok(errors.length===0,'No browser runtime exceptions');
 console.log('Browser checks passed:',checks);
}finally{await browser.close();await new Promise(r=>server.close(r));}
