/* Interface and connection registration. */
state.exclude=store.get('exclude','');state.related=store.get('related',false);state.maxAge=store.get('maxAge',90);
const EXTRA_SOURCES=[
{id:'seacareer',name:'Sea Career',sub:'Chief engineers + superintendent category · public listings and full job details',on:true,kind:'seacareer'},
{id:'marpro',name:'MARPRO',sub:'Maritime technical & shore roles · public listings and full job details',on:true,kind:'marpro'},
{id:'navis',name:'Navis Consulting',sub:'Technical shipping + sea-going roles · public listings and full job details',on:true,kind:'navis'}];
for(const s of EXTRA_SOURCES){if(!DEFAULTS.sources.some(x=>x.id===s.id))DEFAULTS.sources.splice(3,0,s);ADAPTERS[s.id]=(kw,per)=>connected(s.id,per);}
ADAPTERS.faststream=srcFaststream;ADAPTERS.careernet=srcCareernet;
function renderSources(){
 const urls={faststream:'https://www.faststream.com/jobs',spinnaker:'https://spinnaker-global.com/jobs',careernet:'https://www.careernet.gr/aggelies/naftilia',seacareer:'https://www.seacareer.com/chief-engineer-jobs/',marpro:'https://careers.marpro-group.com/jobs',navis:'https://navis-consulting.com/jobs'};
 $('#srcList').innerHTML='<div class="row" style="margin-bottom:12px"><button class="btn small" data-preset="marine">Select all six sources</button><button class="btn small ghost" data-preset="none">Clear selection</button></div>'+state.sources.map((s,i)=>'<div class="src-row"><div class="name">'+esc(s.name)+'<span class="sub">Scheduled public advert digests · <a href="'+urls[s.id]+'" target="_blank" rel="noopener noreferrer">Open source ↗</a></span></div><label class="switch" style="margin:0"><input aria-label="Enable '+esc(s.name)+'" type="checkbox" data-src="'+i+'" '+(s.on?'checked':'')+'><span class="sl"></span></label></div>').join('');
 $$('#srcList [data-src]').forEach(cb=>cb.onchange=()=>{state.sources[+cb.dataset.src].on=cb.checked;store.set('sources',state.sources);updateConnectionCount();});
 $$('#srcList [data-preset]').forEach(b=>b.onclick=()=>{state.sources.forEach(s=>s.on=b.dataset.preset==='marine');store.set('sources',state.sources);renderSources();updateConnectionCount();});
}
function updateConnectionCount(){const el=$('#connectionCount');if(el)el.textContent=state.sources.filter(s=>s.on).length+' snapshot sources selected';}
function syncSettings(){
 $('#useAI').checked=!!state.ai.enabled;$('#aiEndpoint').value=state.ai.endpoint;$('#aiModel').value=state.ai.model;$('#aiBudget').value=state.ai.budget;$('#aiKey').value=state.ai.key||'';
 $('#modePill').classList.toggle('off',!state.ai.enabled);$('#modeTxt').textContent=state.ai.enabled?'Optional AI on':'Private · local matching';
}
function switchTab(name){$$('.tab').forEach(t=>{t.classList.toggle('active',t.dataset.tab===name);t.setAttribute('aria-selected',String(t.dataset.tab===name));});$$('.tab-panel').forEach(p=>p.classList.toggle('active',p.id==='tab-'+name));if(name==='connections')renderHealth();if(name==='pipeline')renderPipeline();if(name==='search')renderPlan();}
function openDetail(id){
 baseOpenDetail(id);const x=state.results.find(x=>x.job.id===id);if(!x)return;
 const s=$('#detailSheet');const extra=document.createElement('div');extra.innerHTML='<div class="divider"></div><h3>Published advert digest</h3><p class="help">'+esc('This is a short excerpt plus automatically extracted advert signals—not the full advert. Open the original source to verify requirements and availability.')+'</p><div class="original-description">'+esc(x.job.desc||'No description supplied.')+'</div>';
 s.appendChild(extra);$('#letterBox').setAttribute('contenteditable','true');$('#letterBox').setAttribute('role','textbox');$('#letterBox').setAttribute('aria-label','Editable cover letter');
 const coverBtn=$('#dCover'),generate=coverBtn.onclick;coverBtn.onclick=async()=>{await generate();const note=document.createElement('p');note.className='help';note.textContent='Editable draft. Verify your name, qualifications and claims before sending. Local regeneration uses the same evidence; it is not an LLM.';if(!$('#letterArea .draft-note')){note.classList.add('draft-note');$('#letterArea').prepend(note);}};
 $('#dCopyLetter').onclick=()=>copyText($('#letterBox').innerText);$('#dPrintLetter').onclick=()=>{buildLetterPrint($('#letterBox').innerText);window.print();};
 const close=$('#dClose');close.setAttribute('aria-label','Close job details');close.textContent='Close';s.prepend(close);close.classList.add('sheet-close');
 $('#detail').setAttribute('role','dialog');$('#detail').setAttribute('aria-modal','true');$('#detail').setAttribute('aria-label',x.job.title);close.focus();
}
function addToTracker(job,score,tcv){if(state.tracker.some(t=>t.id===job.id)){toast('Already saved.','ok');return;}state.tracker.unshift({id:job.id,title:job.title,company:job.company,location:job.location,url:safeUrl(job.url),source:job.source,score:score.total,g:score.G.verdict,status:'Saved',note:'',added:nowISO(),applied:'',cv:tcv||null});store.set('tracker',state.tracker);renderTracker();renderPipeline();toast('Job saved to Applications.','ok');}
function renderTracker(){baseRenderTracker();$$('#kanban .kb-card').forEach((card)=>{const move=card.querySelector('[data-mv]'),remove=card.querySelector('[data-rm]');if(!remove)return;const id=remove.dataset.rm,t=state.tracker.find(x=>x.id===id);if(!t)return;card.querySelectorAll('[data-mv]').forEach(x=>x.remove());const select=document.createElement('select');select.setAttribute('aria-label','Application status for '+t.title);select.style.cssText='font-size:11px;padding:6px;width:100%;margin-top:10px';select.innerHTML=STATUSES.map(st=>'<option '+(st===t.status?'selected':'')+'>'+st+'</option>').join('');select.onchange=()=>{t.status=select.value;if(t.status==='Applied'&&!t.applied)t.applied=nowISO();store.set('tracker',state.tracker);renderTracker();};card.appendChild(select);const note=document.createElement('textarea');note.placeholder='Notes / next action';note.setAttribute('aria-label','Notes for '+t.title);note.value=t.note||'';note.rows=2;note.style.cssText='font-size:11px;margin-top:8px';note.onchange=()=>{t.note=note.value;store.set('tracker',state.tracker);};card.appendChild(note);remove.setAttribute('aria-label','Remove saved job');remove.onclick=()=>{if(!confirm('Remove this job from your application tracker?'))return;state.tracker=state.tracker.filter(x=>x.id!==id);store.set('tracker',state.tracker);renderTracker();renderPipeline();};});}
function bootV2(){
 const allowed=new Set(['faststream','spinnaker','careernet','seacareer','marpro','navis']);state.sources=state.sources.filter(s=>allowed.has(s.id));store.set('sources',state.sources);renderSources();
 const snapshot=embeddedSnapshot();if(validSnapshot(snapshot)){publishedSnapshot=snapshot;showSnapshotInfo(snapshot);}
 if(store.get('engineVersion',0)!==2){state.weights={A:25,B:40,C:15,D:10,E:5,F:5};store.set('weights',state.weights);state.results=(state.results||[]).filter(x=>roleFit(x.job,ctx()).ok).map(x=>({job:normJob(x.job),score:localScore(x.job,ctx())}));store.set('results',state.results);store.set('engineVersion',2);renderWeights();}
 $('#exclude').value=state.exclude;$('#related').checked=state.related;$('#maxAge').value=state.maxAge;
 $('#exclude').oninput=e=>{state.exclude=e.target.value;store.set('exclude',state.exclude);renderPlan();};$('#related').onchange=e=>{state.related=e.target.checked;store.set('related',state.related);renderPlan();};$('#maxAge').onchange=e=>{state.maxAge=Number(e.target.value);store.set('maxAge',state.maxAge);};
 $('#btnStop').onclick=()=>{scanAbort?.abort();$('#btnStop').disabled=true;log('Stopping requests… Previous results will be kept.');};$('#btnStop').disabled=true;
 for(const id of ['cv','prefs','targetRoles','keywords'])$('#'+id).addEventListener('input',()=>{renderPlan();$('#briefChanged').textContent='Search brief updated. Run a new search to refresh existing matches.';});
 $('#focusList').addEventListener('click',renderPlan);$('#regionList').addEventListener('click',renderPlan);$('#btnPlan').onclick=()=>{suggestFromCV(false);renderPlan();};
 $('#resultSearch').oninput=renderPipeline;$('#btnConnections').onclick=()=>switchTab('connections');
 $$('.tab').forEach(t=>{t.setAttribute('role','tab');t.tabIndex=0;t.setAttribute('aria-controls','tab-'+t.dataset.tab);t.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();switchTab(t.dataset.tab);}};});
 $$('label').forEach(l=>{if(l.hasAttribute('for')||l.querySelector('input'))return;const next=l.nextElementSibling;if(next&&['INPUT','TEXTAREA','SELECT'].includes(next.tagName)&&next.id)l.htmlFor=next.id;});
 document.addEventListener('keydown',e=>{if(!$('#detail').classList.contains('open'))return;if(e.key==='Escape'){$('#detail').classList.remove('open');$('#resultSearch').focus();}if(e.key==='Tab'){const els=[...$('#detailSheet').querySelectorAll('button:not(:disabled),a,input,select,textarea,[contenteditable]')].filter(el=>el.offsetParent!==null);if(!els.length)return;const first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
 $('#btnDemo').onclick=()=>{if(state.cv.trim()&&!confirm('Replace your current CV and brief with a fictional test profile? Export a backup first if needed.'))return;state.cv='DEMO CANDIDATE — fictional test profile\nNikos Example\nChief Engineer and Technical Superintendent\nChief Engineer Certificate of Competency STCW III/2, Class 1 CoC.\nChief Engineer on oil and chemical tankers, 2014–2022.\nTechnical Superintendent at Example Ship Management, 2022–2026.\nExperience: dry docking, planned maintenance PMS, MAN B&W engines, Wärtsilä, ISM, SOLAS, MARPOL, class surveys, repair management and budget management.\nLanguages: English, Greek.\nNo LNG or LPG experience.';state.targetRoles='Chief Engineer, Technical Superintendent, Superintendent Engineer';state.prefs='Prefer Greece. Open to worldwide sea-going rotation and shore roles in Europe. Avoid: junior roles, yachts.';state.regions={greece:true,remote:false,europe:true,mideast:false,asia:false,americas:false,world:true};state.focus={sea:true,shore:true};saveAll();syncAll();suggestFromCV(true);renderPlan();toast('Fictional demo profile loaded. Run a live search to test.','ok');};
 // Keep secrets out of persistent storage and backups. A page reload clears the key.
 state.ai.key='';store.set('ai',{...state.ai,key:''});$('#aiKey').value='';
 const persistAI=()=>store.set('ai',{...state.ai,key:''});
 for(const id of ['aiEndpoint','aiModel','aiBudget','useAI'])$('#'+id).addEventListener(id==='useAI'||id==='aiBudget'?'change':'input',persistAI);
 $('#aiKey').oninput=e=>{state.ai.key=e.target.value;persistAI();};
 $('#btnReset').onclick=()=>{if(!confirm('Delete locally stored CV, searches, results and applications?'))return;for(const k of ['cv','targetRoles','keywords','prefs','perSource','weights','ai','sources','customUrl','regions','focus','results','tracker','theme','exclude','related','maxAge','lastScan','engineVersion','sourcesVersion'])store.del(k);location.reload();};
 try{localStorage.setItem('marinepath.storage-test','ok');localStorage.removeItem('marinepath.storage-test');}catch(e){toast('Browser storage unavailable. Use Backup before closing this page.','err');}
 renderPlan();renderHealth();renderPipeline();updateConnectionCount();
}
document.addEventListener('DOMContentLoaded',bootV2);
